Fixes for CUDA 9.2 (GCC-489, #977)
Description: Fixes issues with CUDA 9.2 compilation.

Details:
- CUDA9.2 doesn't like some parts of boost::fusion resulting in `convert_iterator.hpp(57): error: identifier "" is undefined in device code`. The fix is to replace these parts by std::tuple.
- tuple_util::apply was added (without support for invoking on member functions)
- permute_to was rewritten using tuples
- CUDA9.2 doesn't like boost::optional in its standard implementation. For version exactly 9.2 we enable the "old" optional implementation.

Issues: The code compiles fine on my computer with CUDA 9.2 but some tests fail at runtime, while they work (with these changes and the boost::optional workaround) with CUDA 8.0.